stages:
  - build
  - test

build-testing-image:
  stage: build
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    changes:
      - "DESCRIPTION"
      - "Dockerfile"
  when: always

test-package:
  stage: test
  image: $CI_REGISTRY_IMAGE:latest
  before_script:
  script:
    - Rscript -e "devtools::install_dev_deps()"
    - Rscript -e "devtools::document()"
    - Rscript -e "devtools::install()"
    # Number in URL is ID of REPEL API project
    - >
      Rscript -e "devtools::check()" && if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
        curl --request POST --form "token=$CI_JOB_TOKEN" --form "variables[PKG_COMMIT]=$CI_COMMIT_SHA" --form ref=master https://gitlab.com/api/v4/projects/14312994/trigger/pipeline
      fi
  when: on_success



