---
title: "REPEL Travelcast Model - ASF in the Dominican Republic"
output: html_document
---

```{r setup, include=FALSE, cache = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 7, fig.height = 5)
devtools::load_all()
library(ggplot2)
library(ggalt)
library(knitr)
library(cowplot)
conn <- repeldata::repel_remote_conn()
```

### ASF Outbreak Probability in North America over last 3 years
```{r dr-last-yr}
americas <- countrycode::codelist %>% 
  filter(continent == "Americas") %>% 
  pull(iso3c)

current_month <- floor_date(Sys.Date(), unit = "month")
prev_year <- floor_date(current_month - 3*365, unit = "month")
months <- seq(from = prev_year, to = current_month, by = "month")

asf_outbreak_in_americas <- tbl(conn,  "network_lme_augment_predict") %>%
  filter(disease %in% "african_swine_fever")  %>%
  filter(country_iso3c %in% americas) %>%
  filter(month %in% months) %>% 
  collect() %>% 
  mutate("Predicted Outbreak Probability (%)" = predicted_outbreak_probability * 100 )

asf_outbreak_in_dom <- asf_outbreak_in_americas %>% 
  mutate(country_label = case_when(
    country_iso3c == "USA" ~ "United States",
    country_iso3c == "DOM" ~ "Dominican Republic",
    TRUE ~ "other"
  )) %>% 
  mutate(country_label = factor(country_label, levels = c("United States", "Dominican Republic", "other"), ordered = TRUE))

ggplot(asf_outbreak_in_dom, aes(x = month, y = `Predicted Outbreak Probability (%)`, group = country_iso3c,
                                color = country_label, alpha = country_label)) + 
  geom_line() + 
  scale_color_manual(values = c("other" = "gray50", "United States" = "blue", "Dominican Republic" = "maroon2"), guide = "none") +
  scale_alpha_manual(values = c("other" = 0.5, "United States" = 1, "Dominican Republic" = 1), guide = "none") +
  geom_text(data=filter(asf_outbreak_in_dom, 
                        country_iso3c == "DOM", month == max(month)),
            aes(x=month, y=`Predicted Outbreak Probability (%)`, label="Dominican Republic"),
            color="maroon2", size=5, vjust=-1, hjust=1, fontface="bold") +
  geom_text(data=filter(asf_outbreak_in_dom, 
                        country_iso3c == "USA", month == max(month)),
            aes(x=month, y=`Predicted Outbreak Probability (%)`, label="USA"),
            color="blue", size=5, vjust=-1, hjust=1, fontface="bold") +
  labs(x = "",color = "") +
  theme_classic()

```


```{r americas-june}
# ASF Outbreak Probability in the Americas in June (pre-outbreak)
asf_outbreak_in_americas_june <- asf_outbreak_in_americas %>% 
  filter(month == "2021-06-01") %>% 
  arrange(predicted_outbreak_probability) %>% 
  mutate(country = countrycode::countrycode(country_iso3c, origin = "iso3c", destination = "country.name")) %>% 
  mutate(country = forcats::fct_inorder(country))

# ggplot(asf_outbreak_in_americas_june, aes(x = country, y = `Predicted Outbreak Probability (%)`)) +
#   geom_point() + 
#   coord_flip() +
#   theme_classic()
```

```{r probability-hist}
# Are these probabilities "high"? - compare to full outbreak probability dist

all_probabilities <-  tbl(conn,  "network_lme_augment_predict") %>% 
  select(predicted_outbreak_probability) %>% 
  collect() %>% 
  mutate("Predicted Outbreak Probability (%)" = predicted_outbreak_probability * 100 )

# ggplot() +
#   geom_histogram(data = all_probabilities, aes(x = `Predicted Outbreak Probability (%)`)) + 
#   scale_x_log10() + 
#   geom_vline(data = asf_outbreak_in_americas_june %>%
#                filter(country_iso3c %in% c("USA", "DOM")), 
#              aes(xintercept =  `Predicted Outbreak Probability (%)`, color = country_iso3c)) + 
#   theme_classic()

# quantile(all_probabilities$predicted_outbreak_probability)
# 75%tile = 0.0005642402
# DR =  0.0002116481

dom <-  tbl(conn,  "network_lme_augment_predict") %>%
  filter(disease %in% "african_swine_fever") %>% 
  filter(month == "2021-06-01", country_iso3c == "DOM") %>% 
  collect()

## fao heads
# from 2019
# hard to get up to date predictions without current data
# also DR is not a reporting country to FAO
```

### What variables are most important in predicting spread of ASF globally?
```{r variable-importance-overall}
randef <- tbl(conn, "network_lme_coefficients") %>% collect()

randef %>%
  #filter(str_detect(variable, "from_outbreaks")) %>%
  filter(disease == "african_swine_fever") %>%
  filter(!str_detect(variable, "continent")) %>% 
  mutate(variable_clean = forcats::fct_reorder(variable_clean, coef)) %>%
  mutate(pos = coef > 0) %>%
  ggplot() +
  geom_hline(aes(yintercept = 0), color = "gray50") +
  geom_point(aes(x = variable_clean, y = coef, color = pos), size = 2) +
  geom_segment(aes(x = variable_clean, xend = variable_clean, y = coef, yend = 0, color = pos)) +
  #    scale_y_continuous(limits = c(xmin,  xmax)) +
  scale_color_manual(values = c("TRUE" = "#0072B2", "FALSE" = "#D55E00")) +
  labs(y = "Coefficient", x = "") +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "none",
        axis.text = element_text(size = 12),
        title = element_text(size = 12),
        plot.title.position = "plot") +
  NULL

```

```{r variable-importance-dr}
# What variables are most important in predicting outbreak of ASF in the DR?
vi_dom <- get_network_variable_importance(conn,
                                          country_iso3c = "DOM",
                                          diseases = "african_swine_fever",
                                          month = "2021-06-01")


outbreak_prob <- signif(unique(vi_dom$predicted_outbreak_probability), 2)
country_name <- unique(vi_dom$country)
disease_name <- unique(vi_dom$disease_clean)
year <- year(unique(vi_dom$month))

# vi_dom %>%
#   filter(!variable %in% c("disease_country_combo_unreported", "continentAmericas")) %>% 
#   mutate(variable_clean = forcats::fct_reorder(variable_clean, variable_importance)) %>%
#   ggplot() +
#   geom_vline(aes(xintercept = 0), color = "gray50") +
#   geom_point(aes(x = variable_importance, y = variable_clean, color = pos), size = 2) +
#   geom_segment(aes(x = variable_importance, xend = 0, y = variable_clean, yend = variable_clean, color = pos)) +
#   scale_color_manual(values = c("TRUE" = "#0072B2", "FALSE" = "#D55E00")) +
#   labs(y = "", x = "Variable importance", title = glue::glue("{year} {disease_name} Outbreak in {country_name} Variable Importance ({outbreak_prob} probability outbreak)")) +
#   theme_minimal() +
#   theme(legend.position = "none",
#         axis.text = element_text(size = 10),
#         title = element_text(size = 10),
#         plot.title.position = "plot") +
#   NULL

```

### How will outbreak in DR impact outbreak risk other countries?
```{r dr-impact}
asf_outbreak_in_americas_june_aug <- asf_outbreak_in_americas %>% 
  filter(month == "2021-06-01" | month == "2021-08-01") %>% 
  select(country_iso3c, month, `Predicted Outbreak Probability (%)`) %>% 
  mutate(country = countrycode::countrycode(country_iso3c, origin = "iso3c", destination = "country.name")) %>% 
  pivot_wider(names_from = month, values_from = `Predicted Outbreak Probability (%)`) %>% 
  mutate(diff = `2021-08-01` - `2021-06-01`) %>% 
  arrange(diff) %>% 
  mutate(country = forcats::fct_inorder(country)) 

ggplot(asf_outbreak_in_americas_june_aug) +
  geom_dumbbell(aes(y=country, x=`2021-06-01`, xend=`2021-08-01`),
                size=1.5, color="#b2b2b2", size_x=3, size_xend = 3, colour_x = "steelblue1", colour_xend = "maroon1") +
  geom_text(data=filter(asf_outbreak_in_americas_june_aug, diff == max(diff)),
            aes(x=`2021-06-01`, y=country, label="June 2021"),
            color="steelblue1", size=4, vjust=0.25, hjust=1.2, fontface="bold") +
  geom_text(data=filter(asf_outbreak_in_americas_june_aug, diff == max(diff)),
            aes(x=`2021-08-01`, y=country, label="August 2021"),
            color="maroon1", size=4, vjust=0.25, hjust=-0.3, fontface="bold") +
  labs(x = "Predicted Outbreak Probability (%)", y = "") +
  theme_classic()

```

### What countries are the top contributers to ASF outbreak risk in August 2021? 
```{r na-contrib}

asf_outbreak_in_americas_import_risk <- get_network_origin_contribution_import_risk(conn, 
                                                                                    country_iso3c = c("USA", "MEX", "CAN",
                                                                                                      "HTI", "COL", "CUB"),
                                                                                    diseases =  "african_swine_fever",
                                                                                    month = "2021-08-01")

plots <- asf_outbreak_in_americas_import_risk %>% 
  mutate(country_iso3c = factor(country_iso3c, levels = c("USA", "MEX", "CAN", "HTI", "COL", "CUB"))) %>% 
  arrange(country_iso3c, -contribution_to_import_risk) %>% 
  mutate(is_dr = country_origin_iso3c == "DOM") %>% 
  group_split(country_iso3c) %>% 
  map(function(x){
    xmod <- x %>% 
      slice(1:10) %>% 
      arrange(contribution_to_import_risk) %>% 
      mutate(country_origin = forcats::fct_inorder(country_origin)) 
    
    title <- unique(xmod$country)
    ggplot(xmod, aes(y = country_origin, x = contribution_to_import_risk, color = is_dr)) +
      geom_point() +
      geom_hline(aes(yintercept = 0), color = "gray50") +
      geom_segment(aes( xend = 0, yend = country_origin)) +
      scale_color_manual(values = c(`FALSE` = "black", `TRUE` = "deeppink3"), guide = "none") +
      labs(x = "", y = "", title = title) +
      theme_minimal()
  })


cowplot::plot_grid(plotlist = plots)



```

```{r disconn}
dbDisconnect(conn)
```

