---
title: "REPEL network eval"
output: 
  html_document:
    keep_md: TRUE
---

<small>_Click on the_ ▶ _︎arrows to expand sections._</small>


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 7, fig.height = 5)
devtools::load_all()
library(ggplot2)
library(lme4)
library(binom)
library(knitr)
library(forcats)
library(brms)
library(bayestestR)
library(tidybayes) #extract and visualize tidy data frames of draws from posterior distributions of model variables, fits, and predictions from brms::brm

cbp1 <- c("#999999", "#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
predictor_vars <- c("continent", "shared_borders_from_outbreaks",
                    "ots_trade_dollars_from_outbreaks","fao_livestock_heads_from_outbreaks",
                    "n_migratory_wildlife_from_outbreaks",
                    "gdp_dollars", "human_population", "target_taxa_population", "veterinarian_count")
# training data
augmented_data_training <- vroom::vroom(here::here("tmp/network_augmented_data.csv.gz"))  %>%
  select(country_iso3c, disease, month, outbreak_start, !!predictor_vars)

# validated
# model_object <- network_lme_model()
# conn <- repeldata::repel_local_conn()
# valdat <- repel_validation(model_object, conn) %>%
#   select(country_iso3c, disease, month)
# 
# augmented_data_val <- repel_augment(model_object, conn, newdata = valdat)
# vroom::vroom_write(augmented_data_val, gzfile("tmp/network_augmented_data_val.csv.gz"))
augmented_data_val <- vroom::vroom(here::here("tmp/network_augmented_data_val.csv.gz"))  %>%
  select(country_iso3c, disease, month, outbreak_start, !!predictor_vars)

# resample validation
augmented_data_val_bootstrap <- augmented_data_val %>%
  rsample::bootstraps(times = 1) %>%
  pull(splits) %>%
  magrittr::extract2(1) %>%
  as_tibble()

```

### lme4
```{r lme mods}
# Load model
model_object <-  network_lme_model(
  network_model = aws.s3::s3readRDS(bucket = "repeldb/models", object = "lme_mod_network.rds"),
  network_scaling_values = aws.s3::s3readRDS(bucket = "repeldb/models", object = "network_scaling_values.rds")
)
lme_mod <- model_object$network_model
network_scaling_values <- model_object$network_scaling_values
```

```{r prep-lme-coef-plots}
# Random effects
randef <- ranef(lme_mod)
randef_disease <- randef$disease %>%
  tibble::rownames_to_column(var = "disease") %>%
  as_tibble() 

randef_disease_long <- randef_disease %>%
  pivot_longer(-disease, names_to = "variable", values_to = "coef") 

randef_disease_long_formatted <- randef_disease_long %>% 
  mutate(variable = str_replace(variable, "_from_outbreaks", " from countries with existing outbreak"),
         #   variable = str_replace(variable, "ots_trade_dollars", "trade value of animal products"),
         variable = str_replace(variable, "fao_trade_", ""),
         variable = str_replace(variable, "_other", " (other)"),
         variable = str_replace_all(variable, "_", " "),
         variable = str_remove(variable, "continent"),
         variable = str_replace(variable, "shared borders from countries with existing outbreak", "shared borders with country with existing outbreak"))

lme_coeffs <- purrr::map(unique(randef_disease_long_formatted$variable), function(var){
  dat <- randef_disease_long_formatted %>%
    filter(variable == var) %>%
    mutate(pos = coef > 0)
  
  dat <- dat %>% 
    filter(disease %in% get_oie_high_importance_diseases()) %>% 
    mutate(disease = str_replace_all(disease, "_", " ")) %>% 
    mutate(disease = forcats::fct_reorder(disease, coef))
  title <- var
  ggplot(dat) +
    geom_hline(aes(yintercept = 0), color = "gray50") +
    geom_point(aes(x = disease, y = coef, color = pos), size = 2) +
    geom_segment(aes(x = disease, xend = disease, y = coef, yend = 0, color = pos)) +
    #    scale_y_continuous(limits = c(xmin,  xmax)) +
    scale_color_manual(values = c("TRUE" = "#0072B2", "FALSE" = "#D55E00")) +
    labs(y = "Coefficient", x = "", title = title) +
    coord_flip() +
    theme_minimal() +
    theme(legend.position = "none", 
          axis.text = element_text(size = 12), 
          title = element_text(size = 12),
          plot.title.position = "plot") +
    NULL
  
})


names(lme_coeffs) <- unique(randef_disease_long_formatted$variable)

```


```{r lme-var-by-disease, include = FALSE}
src_lme <- map_chr(seq_along(lme_coeffs), ~ {
  tab_name <- names(lme_coeffs[.x])
  knit_expand(text = c("<details>",
                       "<summary>{{tab_name}}</summary>",
                       "```{r lme-coef-{{.x}}, echo = FALSE, align = 'left'}", 
                       "lme_coeffs[[{{.x}}]]",
                       "```",
                       "</details>"))
})

```

`r knit_child(text = src_lme)`

```{r lme-country-predictors}
# for each country and disease, get relative importance
# var_importance_by_country <- augmented_data_training %>%
#   mutate(outbreak_start_predicted = repel_predict(model_object, .)) %>%
#   pivot_wider(names_from = continent, values_from = continent, names_prefix = "continent") %>% 
#   mutate_at(vars(starts_with("continent")), ~ifelse(!is.na(.), 1, NA)) %>% 
#   pivot_longer(cols = -c("country_iso3c", "disease", "month", "outbreak_start", "outbreak_start_predicted"), names_to = "variable", values_to = "x") %>%
#   drop_na(x) %>% 
#   left_join(randef_disease_long) %>%
#   mutate(variable_importance = x * coef) %>%
#   mutate(pos = variable_importance > 0)
# 
# # look at countries with ASK outbreak in 2019
# disease_select <-  "african_swine_fever"
# 
# asf_var_importance <- var_importance_by_country %>%
#   filter(outbreak_start, disease == disease_select)  %>%
#   filter(month >= "2019-01-01") %>%
#   select(-month) %>%
#   distinct()  %>%
#   arrange(-outbreak_start_predicted)
# 
# vp_plots <- map(unique(asf_var_importance$country_iso3c), function(iso3c){
# 
#   tmp <- asf_var_importance %>%
#     filter(country_iso3c == iso3c)
# 
#   country_name <- countrycode::countrycode(iso3c, origin = "iso3c", destination = "country.name")
#   outbreak_prob <- signif(unique(tmp$outbreak_start_predicted), 2)
# 
#   ggplot(tmp) +
#     geom_vline(aes(xintercept = 0), color = "gray50") +
#     geom_point(aes(x = variable_importance, y = variable, color = pos), size = 2) +
#     geom_segment(aes(x = variable_importance, xend = 0, y = variable, yend = variable, color = pos)) +
#     scale_color_manual(values = c("TRUE" = "#0072B2", "FALSE" = "#D55E00")) +
#     labs(y = "", x = "Variable importance", title = glue::glue("2019 ASF Outbreak in {country_name} Variable Importance ({outbreak_prob} probability outbreak)")) +
#     theme_minimal() +
#     theme(legend.position = "none",
#           axis.text = element_text(size = 10),
#           title = element_text(size = 10),
#           plot.title.position = "plot") +
#     NULL
# })
# 
# for (i in 1:length(vp_plots)){
#   print(vp_plots[[i]])
# }

```

<details>
<summary>validation</summary>
```{r lme-validation}
lme_predict <-  augmented_data_val_bootstrap %>%
  select(-month, -outbreak_start) %>%
  mutate(outbreak_start_predicted = repel_predict(model_object, .))

# simple prediction versus actual
# lme_predict %>%
#   mutate(outbreak_start_actual = as.numeric(outbreak_start)) %>%
#   ggplot(aes(x = outbreak_start_predicted, outbreak_start_actual)) +
#   geom_point()

# get predicted outbreak start probability by condition - break into groups by forecasted probability
lme_predict_compressed <- lme_predict %>%
  distinct() %>%
  rename(outbreak_start_predict_prob = outbreak_start_predicted) %>%
  mutate(outbreak_start_predict_prob_grp = cut_number(outbreak_start_predict_prob, n = 30)) %>%
  group_by(outbreak_start_predict_prob_grp) %>%
  mutate(outbreak_start_predict_prob_grp_median = median(outbreak_start_predict_prob)) %>%
  ungroup()

# confirm we get the same prediction when conditions are the same
lme_predict_compressed %>%
  group_by_at(vars(-outbreak_start_predict_prob)) %>%
  count() %>%
  ungroup()  %>%
  nrow() %>%
  assertthat::are_equal(. , nrow(lme_predict_compressed))

# to get actual probability, bring in data from full dataset that applies to the given conditions
lme_binoms <- augmented_data_training %>%
  bind_rows(augmented_data_val) %>%
  right_join(lme_predict_compressed) %>% # joins by condition - gets every actual instance of this condition from which to calculate actual probability
  drop_na() %>%  # dont include unknowns
  group_by(outbreak_start_predict_prob_grp) %>%
  group_split() %>%
  purrr::map_dfr(., function(tw){
    binom <-  binom.confint(x = sum(tw$outbreak_start), n=nrow(tw), methods = "wilson")
    tw %>%
      distinct(outbreak_start_predict_prob_grp, outbreak_start_predict_prob_grp_median) %>%
      mutate(outbreak_start_actual_prob = binom$mean, outbreak_start_actual_low = binom$lower, outbreak_start_actual_upper = binom$upper)})

options(scipen = 999)
ggplot(lme_binoms, aes(x = outbreak_start_predict_prob_grp_median, y  = outbreak_start_actual_prob)) +
  geom_abline(color = "gray50") +
  geom_errorbar(aes(ymin = outbreak_start_actual_low, ymax = outbreak_start_actual_upper)) +
  geom_point(pch = 21,fill = "white") +
  scale_x_continuous(limits = c(0, max(lme_binoms$outbreak_start_actual_upper))) +
  scale_y_continuous(limits = c(0, max(lme_binoms$outbreak_start_actual_upper))) +
  labs(x = "Forecasted probability", y = "Actual probabilty",
       caption = paste("Forecasted probilities are binned into", n_distinct(lme_binoms$outbreak_start_predict_prob_grp_median), "groups by distribution density.\nActual probabilities are  binomial probabilities and confidence intervals for actual outbreaks occurring within the forecasted interval")) +
  theme_minimal() +
  theme(legend.position = "none",
        axis.text = element_text(size = 12),
        title = element_text(size = 12),
        plot.title.position = "plot",
        plot.caption = element_text(hjust = 0)) +
  NULL

```
</details>


### brms
```{r brms-mods}
model_object <-  network_brms_model(
  network_model = aws.s3::s3readRDS(bucket = "repeldb/models", object = "brms_mod_network.rds"),
  network_scaling_values = aws.s3::s3readRDS(bucket = "repeldb/models", object = "network_scaling_values.rds")
)

brms_mod <- model_object$network_model
network_scaling_values <- model_object$network_scaling_values

brms_post <- brms_mod %>%
  spread_draws(r_disease[disease,name])  %>% 
  filter(disease %in% get_oie_high_importance_diseases()) %>% 
  mutate(disease = str_replace_all(disease, "_", " ")) %>% 
  mutate(name = str_remove(name, "continent"),
         name = str_replace(name, "_from_outbreaks", " from countries with existing outbreak"),
         name = str_replace(name, "ots_trade_dollars", "trade value of animal products"),
         name = str_replace(name, "fao_trade_", ""),
         name = str_replace(name, "_other", " (other)"),
         name = str_replace_all(name, "_", " "),
         name = str_replace(name, "shared borders from countries with existing outbreak", "shared borders with country with existing outbreak")) 
```


```{r prep-brms-coef-plots}
brms_coefs <- purrr::map(unique(brms_post$name), function(var){
  dat <- brms_post %>%
    filter(name == var)  %>% 
    mutate(r_disease_med = median(r_disease)) %>% 
    ungroup()
  
  ggplot(dat, aes(y = fct_reorder(disease, r_disease_med), x = r_disease)) +
    stat_halfeye(.width = c(.90, .5))   +
    labs(x = "Coefficient", y = "", title = var) +
    theme_minimal() +
    theme(legend.position = "none", 
          axis.text = element_text(size = 12), 
          title = element_text(size = 12),
          plot.title.position = "plot") +
    NULL
  
})
names(brms_coefs) <- unique(brms_post$name)
```

```{r, include = FALSE}
src_brm <- map_chr(seq_along(brms_coefs), ~ {
  tab_name <- names(brms_coefs[.x])
  knit_expand(text = c("<details>",
                       "<summary>{{tab_name}}</summary>",
                       "```{r brm-coef-{{.x}}, echo = FALSE, align = 'left'}", 
                       "brms_coefs[[{{.x}}]]",
                       "```",
                       "</details>"))
})
```
`r knit_child(text = src_brm)`


<details>
<summary>validation</summary>
```{r brm-validation}
# tic()
# brms_predict <- split(augmented_data_val_bootstrap, (as.numeric(rownames(augmented_data_val_bootstrap))-1) %/% 5000) %>%   purrr::map_dfr(function(x){
#     fitted_draws(model = brms_mod, newdata = x, n = 100, allow_new_levels = TRUE) %>%
#     summarize(estimate = mean(.value)) %>%
#     ungroup()
# })
# #vroom::vroom_write(brms_predict, here::here("tmp/network_validation_brms_predict.csv.gz"))
# toc()

# tic()
# brms_predict <- repel_predict(model_object, augmented_data_val_bootstrap)
# vroom::vroom_write(brms_predict, here::here("tmp/network_validation_brms_predict.csv.gz"))
# toc()
# predictions have randomness, multiple predicitons per condition, in separate groups. 
# get actual by condition, assign to multiple groups?
# or just get actual from validation set?
# going with latter option for now (ie not including training data in actual prob)
brms_predict <- vroom::vroom(here::here("tmp/network_validation_brms_predict2.csv.gz"))  %>% 
  drop_na() %>% 
  rename(outbreak_start_predict_prob = estimate) %>% 
  mutate(outbreak_start_predict_prob_grp = cut_interval(outbreak_start_predict_prob, n = 15)) %>% 
  group_by(outbreak_start_predict_prob_grp) %>% 
  mutate(outbreak_start_predict_prob_grp_median = median(outbreak_start_predict_prob)) %>% 
  ungroup()
brms_binoms <- brms_predict %>%
  group_by(outbreak_start_predict_prob_grp) %>%
  group_split() %>%
  purrr::map_dfr(., function(tw){
    binom <-  binom.confint(x = sum(tw$outbreak_start), n=nrow(tw), methods = "wilson")
    tw %>%
      distinct(outbreak_start_predict_prob_grp, outbreak_start_predict_prob_grp_median) %>%
      mutate(outbreak_start_actual_prob = binom$mean, outbreak_start_actual_low = binom$lower, outbreak_start_actual_upper = binom$upper)})
options(scipen = 999)
ggplot(brms_binoms, aes(x = outbreak_start_predict_prob_grp_median, y  = outbreak_start_actual_prob)) +
  geom_abline(color = "gray50") +
  geom_errorbar(aes(ymin = outbreak_start_actual_low, ymax = outbreak_start_actual_upper), width = 0) +
  geom_point(pch = 21,fill = "white") +
  # scale_x_continuous(limits = c(0, max(brms_binoms$outbreak_start_actual_upper))) +
  # scale_y_continuous(limits = c(0, max(brms_binoms$outbreak_start_actual_upper))) +
  labs(x = "Forecasted probability", y = "Actual probabilty",
       caption = paste("Forecasted probilities are binned into", n_distinct(brms_binoms$outbreak_start_predict_prob_grp_median), "groups by distribution density.\nActual probabilities are  binomial probabilities and confidence intervals for actual outbreaks occurring within the forecasted interval")) +
  theme_minimal() +
  theme(legend.position = "none",
        axis.text = element_text(size = 12),
        title = element_text(size = 12),
        plot.title.position = "plot",
        plot.caption = element_text(hjust = 0)) +
  NULL
```
</details>
