---
title: "nowcast model comparison"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(readr)
library(repelpredict)
library(cowplot)
library(yardstick)
library(countrycode)

devtools::load_all()

conn <- repeldata::repel_local_conn()
grouping_vars <- c("country_iso3c", "report_year", "report_semester", "disease", "disease_population", "taxa")

traindat <- repel_cases_train(conn) %>%
  select(all_of(grouping_vars)) %>%
  distinct()
```

## Baseline
This model predicts the last available semester case count (integer) or disease status (binary) for a given country + disease + taxa. `NA` values are imputed as `0`. 

```{r baseline}
augmented_data_baseline <- repel_augment(model_object = nowcast_baseline_model(), conn = conn, newdata = traindat)
predicted_cases_baseline <- repel_predict(model_object = nowcast_baseline_model(), newdata = augmented_data_baseline)
scored_dat_baselinea <- repel_score(model_object = nowcast_baseline_model(), augmented_data = augmented_data_baseline, predicted_cases = predicted_cases_baseline)
scored_data_baseline[-1]
```

## XGBoost
Model and scored results on full training set (using default tuning params)
```{r xgb}
augmented_data_boost <- repel_augment(model_object = nowcast_boost_model(), conn = conn, newdata = traindat)
predicted_cases_boost <- repel_predict(model_object = nowcast_boost_model(), newdata = augmented_data_boost)
scored_data_boost <- repel_score(model_object = nowcast_boost_model(), augmented_data = augmented_data_boost, predicted_cases = predicted_cases_boost)
scored_data_boost[-1]
```

### XGBoost - disease status
```{r xgb2}
disease_status_comp <- augmented_data_boost %>%
  select(all_of(grouping_vars), disease_status_actual = disease_status) %>%
  mutate(disease_status_predicted = as.integer(predicted_cases_boost>0)) %>%
  mutate(disease_status_match = disease_status_actual == disease_status_predicted) %>% 
  mutate(continent = countrycode::countrycode(country_iso3c, origin = "iso3c", destination = "continent")) 

# confusion matrix by taxa
make_conf_mat <- function(grp_var){
  grp_disease_status <- disease_status_comp %>%
    select(all_of(grp_var), disease_status_actual, disease_status_predicted) %>%
    mutate(disease_status_actual = factor(disease_status_actual)) %>%
    mutate(disease_status_predicted = factor(disease_status_predicted))
  
  cm_grp <- grp_disease_status %>%
    group_by_at(grp_var) %>%
    conf_mat(truth = disease_status_actual, estimate = disease_status_predicted)
  
  cm_rates <- cm_grp %>%
    mutate(tidied = map(conf_mat, tidy)) %>%
    unnest(tidied) %>% 
    mutate(true_status = recode(name, "cell_1_1" = "neg", "cell_2_1" = "neg", "cell_1_2" = "pos", "cell_2_2" = "pos")) %>% 
    mutate(classification = recode(name, "cell_1_1" = "correct", "cell_2_1" = "incorrect", "cell_1_2" = "incorrect", "cell_2_2" = "correct")) %>% 
    mutate(x = recode(name, "cell_1_1" = "0", "cell_2_1" = "0", "cell_1_2" = "1", "cell_2_2" = "1")) %>% 
    mutate(y = recode(name,  "cell_1_1" = "0", "cell_2_1" = "1", "cell_1_2" = "0", "cell_2_2" = "1")) %>% 
    group_by_at(c(grp_var, "true_status")) %>%
    mutate(total = sum(value)) %>% 
    ungroup() %>% 
    mutate(rate = value/total) %>% 
    select(all_of(grp_var), true_status, classification, rate, value, x, y)
  
  accur <- cm_rates %>% 
    filter(classification == "correct") %>% 
    mutate(x_lab = paste0(x, "\n(", signif(100*rate, 3), "% accuracy)")) %>% 
    select(all_of(grp_var), x, x_lab)
  
  cm_rates <- left_join(cm_rates, accur)
  
  vars <- cm_rates %>% 
    pull(grp_var) %>% 
    unique()
  
  cm_plots <- map(vars, function(tx){
    
    dat <- cm_rates %>% 
      filter_at(grp_var, ~.x == tx)
    
    ggplot(dat, aes(x_lab, y, label = value)) +
      geom_tile(aes(fill = value), show.legend = FALSE, alpha = 0.5) +
      geom_label(alpha = 0)+
      scale_fill_viridis_c() +
      labs(x = "truth", y = "predicted", title = tx) +
      theme_bw()
  })
  
  plot_grid(plotlist = cm_plots)
}

make_conf_mat("taxa")
make_conf_mat("continent")

```

### XGBoost - cases
```{r xgb3}

```

### XGBoost - partial effects
```{r xgb3}

```



## BART
Model and scored results on full training set
```{r bart}

augmented_data <- read_rds(here::here("tmp/augmented_data.rds"))

#assertthat::are_equal(nrow(traindat), nrow(augmented_data))

bart_mod_cases <- read_rds(here::here("models/bart_mod_cases.rds"))
mod_cases_obj <- bart_mod_cases[[1]]
mod_cases_dat <- bart_mod_cases[[2]]

predicted_disease_status_probability <- read_rds(here::here("models/predicted_disease_status_probability.rds"))
predicted_disease_status <- round(predicted_disease_status_probability)

predicted_cases <- round(apply(mod_cases_obj$yhat.test, 2, mean))
predicted_cases <- ifelse(predicted_cases < 0, 0, predicted_cases)

predicted_disease_status_eval <- augmented_data %>%
  mutate(predicted_disease_status = predicted_disease_status)

predicted_cases_eval <- augmented_data %>%
  drop_na(cases) %>%
  filter(cases > 0) %>%
  mutate(predicted_cases = predicted_cases)

cases_comp <- augmented_data %>%
  drop_na(cases) %>%
  filter(cases > 0) %>%
  select(all_of(grouping_vars), cases_actual = cases, cases_lag1) %>%
  mutate(cases_predicted = predicted_cases) %>%
  mutate(cases_error = abs(cases_actual - cases_predicted)) %>%
  mutate(cases_dirchange_actual = cases_actual - cases_lag1) %>%
  mutate(cases_dirchange_predicted = cases_predicted - cases_lag1) %>%
  mutate_at(.vars = c("cases_dirchange_actual", "cases_dirchange_predicted"),
            ~case_when(. == 0 ~ "no change",
                       . > 0 ~ "increase",
                       . < 0 ~ "decrease",
                       is.na(.) ~ NA_character_)) %>%
  mutate(cases_dirchange_match = cases_dirchange_actual == cases_dirchange_predicted)

disease_status_comp <- augmented_data %>%
  select(all_of(grouping_vars), disease_status_actual = disease_status) %>%
  mutate(disease_status_predicted = predicted_disease_status) %>%
  mutate(disease_status_predicted_probability = predicted_disease_status_probability) %>%
  mutate(disease_status_match = disease_status_actual == disease_status_predicted)

disease_status_confusion_matrix = table(disease_status_comp %>% select(disease_status_actual, disease_status_predicted))
disease_status_prediction_accuracy = sum(disease_status_comp$disease_status_match, na.rm = TRUE)/nrow(disease_status_comp %>% drop_na(disease_status_match))
cases_direction_confusion_matrix = table(cases_comp %>% select(cases_dirchange_actual, cases_dirchange_predicted)) #this automatically removes NA
cases_direction_prediction_accuracy = sum(cases_comp$cases_dirchange_match, na.rm = TRUE)/nrow(cases_comp %>% drop_na(cases_dirchange_match))
mean_abs_error = mean(cases_comp$cases_error, na.rm = TRUE)
p95_abs_error = quantile(cases_comp$cases_error, 0.95, na.rm = TRUE)

print("disease_status_confusion_matrix")
disease_status_confusion_matrix
print("disease_status_prediction_accuracy")
disease_status_prediction_accuracy
print("cases_direction_confusion_matrix")
cases_direction_confusion_matrix
print("cases_direction_prediction_accuracy")
cases_direction_prediction_accuracy
print("mean_abs_error")
mean_abs_error
print("p95_abs_error")
p95_abs_error

# confusion matrix by taxa
taxa_disease_status <- disease_status_comp %>%
  select(taxa, disease_status_actual, disease_status_predicted) %>%
  mutate(disease_status_actual = factor(disease_status_actual)) %>%
  mutate(disease_status_predicted = factor(disease_status_predicted))

cm_taxa <- taxa_disease_status %>%
  group_by(taxa) %>%
  conf_mat(disease_status_actual, disease_status_predicted)

cells_per_taxa <- cm_taxa %>%
  mutate(tidied = map(conf_mat, tidy)) %>%
  unnest(tidied)

counts_per_taxa <- taxa_disease_status %>%
  group_by(taxa) %>%
  summarize(total = n()) %>%
  left_join(cells_per_taxa, by = "taxa") %>%
  # Compute the proportions
  mutate(prop = value/total)

cm_plots <- map(cm_taxa$conf_mat, autoplot, type = "heatmap")
library(cowplot)
plot_grid(plotlist = cm_plots, labels = cm_taxa$taxa)

# confusion matrix by continent
cont_disease_status <- disease_status_comp %>%
  select(country_iso3c, disease_status_actual, disease_status_predicted) %>%
  mutate(continent = countrycode::countrycode(country_iso3c, origin = "iso3c", destination = "continent")) %>%
  mutate(disease_status_actual = factor(disease_status_actual)) %>%
  mutate(disease_status_predicted = factor(disease_status_predicted))

cm_cont <- cont_disease_status %>%
  group_by(continent) %>%
  conf_mat(disease_status_actual, disease_status_predicted)

cells_per_cont <- cm_cont %>%
  mutate(tidied = map(conf_mat, tidy)) %>%
  unnest(tidied)

counts_per_cont <- cont_disease_status %>%
  group_by(continent) %>%
  summarize(total = n()) %>%
  left_join(cells_per_cont, by = "continent") %>%
  # Compute the proportions
  mutate(prop = value/total)

cm_plots <- map(cm_cont$conf_mat, autoplot, type = "heatmap")
library(cowplot)
plot_grid(plotlist = cm_plots, labels = cm_cont$continent)

# cases actual versus residual
cases_comp %>%
  ggplot(., aes(x = cases_actual, y = cases_predicted, color = log10(cases_error))) +
  geom_point(alpha = 0.5) +
  scale_y_log10() +
  scale_x_log10() +
  theme_bw()

```


